version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: centrillion_client
    container_name: centrillion_client
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: centrillion_server
    container_name: centrillion_server
    ports:
      - "5000:5000"