import React from "react";
import Head from "next/head";

import { AddProduct, Layout } from "../components";

export default function AddProductPage() {
  return (
    <>
      <Head>
        <title>Add Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AddProduct />
    </>
  );
}

AddProductPage.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
};
