import React from "react";
import Head from "next/head";

import { SignIn, Layout } from "../components";

export default function SignInPage() {
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignIn />
    </>
  );
}

SignInPage.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
};
